name: PistonExploits
version: ${project.version}
main: net.pistonmaster.pistonexploits.PistonExploits
description: Great addition to 1.12.2 servers to fix various lag and crash exploits!
website: https://pistonmaster.net/
