name: PistonExploits
version: ${project.version}
api-version: 1.13
main: net.pistonmaster.pistonexploits.PistonExploits
description: ${project.description♦}
website: https://pistonmaster.net/
softdepend: ["PlugMan"]
# loadbefore: ["ExploitsX", "L2X9Core", "AnarchyExploitFixes"]